# Generated by Django 4.1.7 on 2023-09-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_logo_image_images_logo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('about', models.TextField(default='')),
                ('link', models.ImageField(upload_to='testmonialsImage')),
                ('portfolio_link', models.URLField(default=None)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('quote', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials_images/')),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
