# Generated by Django 4.1.7 on 2023-09-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_owner_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
