# Generated by Django 4.1.7 on 2023-09-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_owner_delete_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('about', models.TextField(default='')),
                ('image', models.ImageField(upload_to='owner')),
                ('portfolio_link', models.URLField()),
                ('designation', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=225)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('quote', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials_images/')),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
