# Generated by Django 4.1.7 on 2023-09-29 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_owner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='quote',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
