# Generated by Django 4.1.7 on 2023-09-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='nick_name',
            field=models.CharField(default='RS', max_length=40),
            preserve_default=False,
        ),
    ]
