# Generated by Django 4.1.7 on 2023-09-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_owner_nick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headinng', models.CharField(max_length=255)),
                ('sub_headinng', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
