# Generated by Django 4.1.7 on 2023-09-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_skill_created_at_skill_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='headinng',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sub_headinng',
        ),
        migrations.AddField(
            model_name='owner',
            name='blog_headinng',
            field=models.CharField(default='Blogs', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='blog_sub_headinng',
            field=models.CharField(default='Featured Blog', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_headinng',
            field=models.CharField(default='Contacts', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_sub_headinng',
            field=models.CharField(default='feel free to contact!!', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='service_headinng',
            field=models.CharField(default='Services', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='service_sub_headinng',
            field=models.CharField(default='Our latest Services', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='skill_headinng',
            field=models.CharField(default='Skills', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='skill_sub_headinng',
            field=models.CharField(default='My skills', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='testimonial_headinng',
            field=models.CharField(default='Testimonials', max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='testimonial_sub_headinng',
            field=models.CharField(default='Client Response', max_length=255),
        ),
    ]
