# Generated by Django 4.1.7 on 2023-09-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_skill_headinng_remove_skill_sub_headinng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='blog_headinng',
            new_name='blog_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='blog_sub_headinng',
            new_name='blog_sub_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='contact_headinng',
            new_name='contact_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='contact_sub_headinng',
            new_name='contact_sub_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='service_headinng',
            new_name='service_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='service_sub_headinng',
            new_name='service_sub_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='skill_headinng',
            new_name='skill_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='skill_sub_headinng',
            new_name='skill_sub_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='testimonial_headinng',
            new_name='testimonial_heading',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='testimonial_sub_headinng',
            new_name='testimonial_sub_heading',
        ),
    ]
