# Generated by Django 4.1.7 on 2023-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_featureservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureservice',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
