# Generated by Django 4.1.7 on 2023-09-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_featureservice_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureservice',
            name='description',
        ),
    ]
