# Generated by Django 4.1.7 on 2023-09-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_featureservice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='fav_icon',
            field=models.ImageField(default='https://user-images.githubusercontent.com/93479842/271746592-24b4aca9-a750-40b0-bf1b-93907b38c16e.png', upload_to='favicon/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='image',
            field=models.ImageField(upload_to='owner/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='uploaded_file',
            field=models.FileField(upload_to='service/'),
        ),
    ]
