# Generated by Django 4.1.7 on 2023-09-30 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_widgetitem_owner_fav_icon_alter_owner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widgetitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
