# Generated by Django 4.1.7 on 2023-09-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_widgetitem_created_at_widgetitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='hero_bg_color',
            field=models.CharField(default='gray', max_length=225),
        ),
    ]
